#version: '3.8'

services:

  # Web Server Service
  order_nginx:
    image: nginx:alpine
    container_name: order_nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - order_app
      - order_db
    networks:
      - shopping
      
  #Database Service
  order_db:
    image: mysql
    container_name: order_db
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: Order
      MYSQL_ROOT_PASSWORD: password
    networks:
      - shopping

  # Application Service
  order_app:
    container_name: order_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9001:9000"
    working_dir: /var/www
    networks:
      - shopping

  # phpMyAdmin Service
  order_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: order_phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - order_db
    networks:
      - shopping
 
networks:
  shopping:
    external: true